name: Quality check
on:
  push:
    branches:
    - "*"
  pull_request:

permissions:
  contents: read

jobs:
  static-analysis:
    name: Static analysis
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - run: make check

  tests-openbsd:
    name: Tests on OpenBSD
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            api.github.com:443
            pool.ntp.org:443
            cdn.openbsd.org:443
            www.google.com:443
            raw.githubusercontent.com:443
            objects.githubusercontent.com:443
            time.cloudflare.com:443
            ppa.launchpadcontent.net:443
            packages.microsoft.com:443
            azure.archive.ubuntu.com:80
            motd.ubuntu.com:443
            esm.ubuntu.com:443
            pypi.org:443
            files.pythonhosted.org:443

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run tests inside VM
        uses: vmactions/openbsd-vm@0cfe06e734a0ea3a546fca7ebf200b984b94d58a # v1.1.4
        with:
          prepare: pkg_add git shellcheck
          run: |
            make test

  tests-ubuntu:
    name: Tests on Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            github.com:443
            raw.githubusercontent.com:443
            objects.githubusercontent.com:443

      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - run: make test
