name: Static analysis & unit tests
on: [push, pull_request]

jobs:
  Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Unit tests with unittest.sh
      run: TERM=vt100 make test

    - name: Static analysis with shellcheck
      run: make check

  OpenBSD-VM:
    runs-on: macos-12
    name: OpenBSD in VirtualBox on MacOS
    steps:
    - uses: actions/checkout@v3

    - name: Unit tests with unittest.sh
      uses: vmactions/openbsd-vm@v0
      with:
        run: TERM=vt100 make test

    - name: Static analysis with shellcheck
      uses: vmactions/openbsd-vm@v0
      with:
        run: make check
